import { Payment } from "@/app/payment/column";

export const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "pmt-001",
      amount: 100,
      status: "pending",
      email: "user1@example.com",
    },
    {
      id: "pmt-002",
      amount: 200,
      status: "processing",
      email: "user2@example.com",
    },
    {
      id: "pmt-003",
      amount: 150,
      status: "success",
      email: "user3@example.com",
    },
    { id: "pmt-004", amount: 80, status: "failed", email: "user4@example.com" },
    {
      id: "pmt-005",
      amount: 300,
      status: "pending",
      email: "user5@example.com",
    },
    {
      id: "pmt-006",
      amount: 180,
      status: "processing",
      email: "user6@example.com",
    },
    {
      id: "pmt-007",
      amount: 220,
      status: "success",
      email: "user7@example.com",
    },
    { id: "pmt-008", amount: 90, status: "failed", email: "user8@example.com" },
    {
      id: "pmt-009",
      amount: 130,
      status: "pending",
      email: "user9@example.com",
    },
    {
      id: "pmt-010",
      amount: 175,
      status: "processing",
      email: "user10@example.com",
    },

    {
      id: "pmt-011",
      amount: 250,
      status: "success",
      email: "user11@example.com",
    },
    {
      id: "pmt-012",
      amount: 60,
      status: "failed",
      email: "user12@example.com",
    },
    {
      id: "pmt-013",
      amount: 115,
      status: "pending",
      email: "user13@example.com",
    },
    {
      id: "pmt-014",
      amount: 210,
      status: "processing",
      email: "user14@example.com",
    },
    {
      id: "pmt-015",
      amount: 165,
      status: "success",
      email: "user15@example.com",
    },
    {
      id: "pmt-016",
      amount: 145,
      status: "failed",
      email: "user16@example.com",
    },
    {
      id: "pmt-017",
      amount: 195,
      status: "pending",
      email: "user17@example.com",
    },
    {
      id: "pmt-018",
      amount: 230,
      status: "processing",
      email: "user18@example.com",
    },
    {
      id: "pmt-019",
      amount: 175,
      status: "success",
      email: "user19@example.com",
    },
    {
      id: "pmt-020",
      amount: 105,
      status: "failed",
      email: "user20@example.com",
    },

    {
      id: "pmt-021",
      amount: 120,
      status: "pending",
      email: "user21@example.com",
    },
    {
      id: "pmt-022",
      amount: 260,
      status: "processing",
      email: "user22@example.com",
    },
    {
      id: "pmt-023",
      amount: 185,
      status: "success",
      email: "user23@example.com",
    },
    {
      id: "pmt-024",
      amount: 95,
      status: "failed",
      email: "user24@example.com",
    },
    {
      id: "pmt-025",
      amount: 310,
      status: "pending",
      email: "user25@example.com",
    },
    {
      id: "pmt-026",
      amount: 175,
      status: "processing",
      email: "user26@example.com",
    },
    {
      id: "pmt-027",
      amount: 220,
      status: "success",
      email: "user27@example.com",
    },
    {
      id: "pmt-028",
      amount: 85,
      status: "failed",
      email: "user28@example.com",
    },
    {
      id: "pmt-029",
      amount: 135,
      status: "pending",
      email: "user29@example.com",
    },
    {
      id: "pmt-030",
      amount: 200,
      status: "processing",
      email: "user30@example.com",
    },

    {
      id: "pmt-031",
      amount: 245,
      status: "success",
      email: "user31@example.com",
    },
    {
      id: "pmt-032",
      amount: 75,
      status: "failed",
      email: "user32@example.com",
    },
    {
      id: "pmt-033",
      amount: 125,
      status: "pending",
      email: "user33@example.com",
    },
    {
      id: "pmt-034",
      amount: 205,
      status: "processing",
      email: "user34@example.com",
    },
    {
      id: "pmt-035",
      amount: 160,
      status: "success",
      email: "user35@example.com",
    },
    {
      id: "pmt-036",
      amount: 140,
      status: "failed",
      email: "user36@example.com",
    },
    {
      id: "pmt-037",
      amount: 190,
      status: "pending",
      email: "user37@example.com",
    },
    {
      id: "pmt-038",
      amount: 240,
      status: "processing",
      email: "user38@example.com",
    },
    {
      id: "pmt-039",
      amount: 170,
      status: "success",
      email: "user39@example.com",
    },
    {
      id: "pmt-040",
      amount: 100,
      status: "failed",
      email: "user40@example.com",
    },

    {
      id: "pmt-041",
      amount: 110,
      status: "pending",
      email: "user41@example.com",
    },
    {
      id: "pmt-042",
      amount: 270,
      status: "processing",
      email: "user42@example.com",
    },
    {
      id: "pmt-043",
      amount: 180,
      status: "success",
      email: "user43@example.com",
    },
    {
      id: "pmt-044",
      amount: 85,
      status: "failed",
      email: "user44@example.com",
    },
    {
      id: "pmt-045",
      amount: 320,
      status: "pending",
      email: "user45@example.com",
    },
    {
      id: "pmt-046",
      amount: 160,
      status: "processing",
      email: "user46@example.com",
    },
    {
      id: "pmt-047",
      amount: 230,
      status: "success",
      email: "user47@example.com",
    },
    {
      id: "pmt-048",
      amount: 95,
      status: "failed",
      email: "user48@example.com",
    },
    {
      id: "pmt-049",
      amount: 140,
      status: "pending",
      email: "user49@example.com",
    },
    {
      id: "pmt-050",
      amount: 210,
      status: "processing",
      email: "user50@example.com",
    },
  ];
};
